#!/bin/sh
# Byte-compare Phase 1 corpora generated by libraries inside the pinned official
# PDS image. The service is never started; this makes no XRPC or account call.
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(CDPATH= cd -- "$HERE/../.." && pwd)
WORK=$(mktemp -d "${TMPDIR:-/tmp}/pds-phase1-image.XXXXXX")
trap 'rm -rf "$WORK"' EXIT HUP INT TERM

PDS_IMAGE=ghcr.io/bluesky-social/pds@sha256:d95725b24dbe53af9d91dc69750556931ebed6c396f2cfa42b221434db642f12
PDS_REVISION=374cf1d4ba782d4391bbb73e4e2d3f320d4846d6

actual_revision=$(docker image inspect --format '{{ index .Config.Labels "org.opencontainers.image.revision" }}' "$PDS_IMAGE")
[ "$actual_revision" = "$PDS_REVISION" ] || {
  echo 'check_pds_phase1_image: official PDS image revision mismatch' >&2
  exit 1
}

docker run --rm --entrypoint node \
  -v "$HERE:/medaka-tools:ro" \
  -v "$WORK:/medaka-out" \
  "$PDS_IMAGE" \
  /medaka-tools/extract_pds_phase1_corpora.mjs /medaka-tools /medaka-out

cmp "$WORK/mst_reference_corpus.txt" "$ROOT/pds/test/vectors/mst_reference_corpus.txt"
cmp "$WORK/car_reference_corpus.txt" "$ROOT/pds/test/vectors/car_reference_corpus.txt"
cmp "$WORK/repo_reference_corpus.txt" "$ROOT/pds/test/vectors/repo_reference_corpus.txt"

echo "PASS: pinned PDS image libraries (@atproto/repo@0.10.10, @atproto/crypto@0.5.4) reproduce MST/CAR/repo corpora; image=$PDS_IMAGE revision=$PDS_REVISION; no service/XRPC route"
