#!/bin/sh
# cost_baseline_land.sh — the box-side half of the gate-cost baseline
# auto-advance loop (#2180 baseline leg).
#
#   sh scripts/cost_baseline_land.sh [--lander-dir D] [--dry-run]
#
# nightly.yml's `gate-cost-autoadvance` job (test/gate_cost_collect.sh) ends at
# a pushed `cost-baseline-autoadvance-<ts>` branch carrying DATA ONLY: the
# GITHUB_TOKEN may neither open a pull request on this repo nor push a change
# to .github/workflows/ci.yml. Both of those are the steps this script takes,
# from a machine that holds a real `gh` login:
#
#   1. list the remote `cost-baseline-autoadvance-*` branches;
#   2. a branch whose PR is already OPEN: (re)arm auto-merge and move on;
#   3. a branch with no PR: check it out in a dedicated clone, build ./medaka,
#      run `make gen-ci`, amend the regenerated ci.yml onto the commit, push,
#      open the PR, and enqueue it (scripts/pr.sh enqueue — a verified
#      auto-merge, never a bare `gh pr merge` exit code).
#
# The clone under --lander-dir (default /root/cost-lander/medaka) exists so
# that a build here never touches a developer checkout or worktree. A lock file
# keeps overlapping cron firings from building on top of each other.
#
# Runs from cron on the build box; the crontab line is recorded in
# docs/ops/CI-ARCHITECTURE.md §3.5. Idempotent: a run with nothing pending
# does no build and prints one line.
set -u

LANDER_DIR="/root/cost-lander/medaka"
DRY=0
REPO="MedakaLang/medaka"
PREFIX="cost-baseline-autoadvance"
BASE="main"

while [ $# -gt 0 ]; do
  case "$1" in
    --lander-dir) LANDER_DIR="$2"; shift 2 ;;
    --dry-run)    DRY=1; shift ;;
    --repo)       REPO="$2"; shift 2 ;;
    *) echo "cost_baseline_land: unknown argument: $1" >&2; exit 2 ;;
  esac
done

log() { printf '%s cost_baseline_land: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }

branches="$(gh api "repos/$REPO/branches?per_page=100" --paginate \
  --jq ".[].name | select(startswith(\"$PREFIX-\"))" 2>/dev/null | sort)"
if [ -z "$branches" ]; then
  log "no pending $PREFIX-* branch — nothing to do."
  exit 0
fi

lock="$(dirname "$LANDER_DIR")/land.lock"
mkdir -p "$(dirname "$LANDER_DIR")"
if ! mkdir "$lock" 2>/dev/null; then
  log "another run holds $lock — exiting."
  exit 0
fi
trap 'rmdir "$lock" 2>/dev/null' EXIT INT TERM

if [ ! -d "$LANDER_DIR/.git" ]; then
  log "cloning $REPO into $LANDER_DIR"
  git clone --quiet "git@github.com:$REPO.git" "$LANDER_DIR" || exit 1
fi

rc=0
for br in $branches; do
  pr="$(gh pr list --repo "$REPO" --head "$br" --state open --json number --jq '.[0].number' 2>/dev/null)"
  if [ -n "$pr" ]; then
    log "$br: PR #$pr already open — re-arming auto-merge."
    [ "$DRY" = 1 ] || sh "$LANDER_DIR/scripts/pr.sh" enqueue --number "$pr" --repo "$REPO" --timeout 120 || true
    continue
  fi
  # A merged PR deletes its branch (delete_branch_on_merge), so a branch with
  # only a CLOSED PR was abandoned by a human; leave it for them.
  closed="$(gh pr list --repo "$REPO" --head "$br" --state closed --json number --jq '.[0].number' 2>/dev/null)"
  if [ -n "$closed" ]; then
    log "$br: its PR #$closed was closed without merging — leaving the branch alone."
    continue
  fi
  log "$br: no PR yet — regenerating ci.yml and opening one."
  if [ "$DRY" = 1 ]; then continue; fi

  git -C "$LANDER_DIR" fetch --quiet origin "$br" "$BASE" || { rc=1; continue; }
  git -C "$LANDER_DIR" checkout --quiet -B "$br" "origin/$br" || { rc=1; continue; }
  git -C "$LANDER_DIR" clean -fdq -e medaka -e medaka_emitter
  # Build in the clone's own tree; MEDAKA_STRICT=1 makes a stale binary a
  # hard failure rather than a right-looking ci.yml from older source.
  if ! make -C "$LANDER_DIR" medaka >"$(dirname "$LANDER_DIR")/build.log" 2>&1; then
    log "$br: make medaka failed — see $(dirname "$LANDER_DIR")/build.log"
    rc=1; continue
  fi
  if ! MEDAKA_STRICT=1 make -C "$LANDER_DIR" gen-ci >"$(dirname "$LANDER_DIR")/gen-ci.log" 2>&1; then
    log "$br: make gen-ci failed — see $(dirname "$LANDER_DIR")/gen-ci.log"
    rc=1; continue
  fi
  if [ -n "$(git -C "$LANDER_DIR" status --porcelain -- .github/workflows/ci.yml)" ]; then
    git -C "$LANDER_DIR" add .github/workflows/ci.yml
    git -C "$LANDER_DIR" -c user.name=medaka-bot -c user.email=medaka-bot@users.noreply.github.com \
      commit --quiet --amend --no-edit || { rc=1; continue; }
    git -C "$LANDER_DIR" push --quiet --force-with-lease origin "$br" || { rc=1; continue; }
    log "$br: ci.yml regenerated and amended."
  else
    log "$br: ci.yml unchanged by gen-ci."
  fi

  body="Generated by nightly.yml's gate-cost-autoadvance job (test/gate_cost_collect.sh); ci.yml regenerated and the PR opened by scripts/cost_baseline_land.sh from the build box. The diff is exactly what \`medaka gate balance && make gen-ci\` emits from the ingested samples; \`gate-balance\` and \`ci-gen-drift\` verify that in CI."
  url="$(gh pr create --repo "$REPO" --head "$br" --base "$BASE" \
    --title "gate cost: auto-advance baseline ($br)" --body "$body" 2>&1)"
  num="$(printf '%s' "$url" | sed -n 's#.*/pull/\([0-9]*\).*#\1#p')"
  if [ -z "$num" ]; then
    log "$br: gh pr create returned no PR number: $url"
    rc=1; continue
  fi
  log "$br: opened PR #$num — enqueueing."
  sh "$LANDER_DIR/scripts/pr.sh" enqueue --number "$num" --repo "$REPO" --timeout 300 || rc=1
done
exit "$rc"
