#!/usr/bin/env bash
# build_stdlib_docs.sh — render docs/stdlib/*.md into a staging directory of HTML
# pages: the published stdlib reference (#2384).
#
# The sibling of build_guide.sh, over the SAME render machine
# (playground/render_docs.mjs). Not a fork — a second thin entry point, because
# the two doc sets differ only in their arguments: a different title, a
# different exclusion set, and a source set that supplies its own index.md.
#
#   bash playground/build_stdlib_docs.sh                     # docs/stdlib -> playground/site-stdlib
#   bash playground/build_stdlib_docs.sh <src> <out>         # any doc set, any destination
#   bash playground/build_stdlib_docs.sh <src> <out> <dist>  # …and check imports against <dist>
#
# The third argument is the directory of `.mdk` modules the playground page ships
# (playground/dist). Deliberately not defaulted, for the reason build_guide.sh
# gives: dist/ exists only after a wasm build, so defaulting it would make the
# rendered output depend on whether someone had built the wasm.
#
# THE INDEX. `docs/stdlib/index.md` is GENERATED by `medaka doc` — ~905 per-entry
# deep links, one per exported name and instance — and it renders to index.html
# like any other page. render_docs.mjs's synthetic chapter-list index is written
# only for a doc set that has no index.md of its own, so it does not clobber
# this one. Do not add index.md to the exclusion list below: the reference has no
# other table of contents.
#
# THE EXCLUSIONS. Three hand-written design documents live in docs/stdlib/ and
# are NOT the reference:
#   STDLIB.md            "The Medaka Standard Library — Plan": design rationale,
#                        history, and open roadmap. 90 KB, known stale (it still
#                        publishes `replaceWith`, renamed to `mapConst`).
#   FP-STDLIB-DESIGN.md  the functional-core design note.
#   P1-STDLIB-DESIGN.md  the P1 design note.
# The deployed site serves the GENERATED reference. These three keep their
# repository home and stay readable on GitHub — `docs/stdlib/index.md` is what a
# reader is sent to for "does the stdlib have X", and AGENTS.md already routes
# design rationale to STDLIB.md in the repo. Publishing a stale plan document
# beside a generated reference is how a reader ends up trusting the wrong one.
#
# The output directory is a STAGING dir. Wiring it into the deployable site is
# playground/build_site.sh's job (S-3), not this script's.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SRC="${1:-$REPO_ROOT/docs/stdlib}"
OUT="${2:-$SCRIPT_DIR/site-stdlib}"
DIST="${3:-}"

DIST_ARGS=()
if [ -n "$DIST" ]; then
  DIST_ARGS=(--dist "$DIST")
fi

exec node "$SCRIPT_DIR/render_docs.mjs" \
  --src "$SRC" \
  --out "$OUT" \
  --exclude STDLIB.md,FP-STDLIB-DESIGN.md,P1-STDLIB-DESIGN.md \
  --title "The Medaka Standard Library" \
  --repo-root "$REPO_ROOT" \
  "${DIST_ARGS[@]+"${DIST_ARGS[@]}"}"
