#!/usr/bin/env bash
# build_marked.sh — ONE-TIME offline vendoring of the `marked` Markdown parser into
# a single self-contained ESM bundle committed at vendor/marked/marked.js.
#
# This is a build-TIME step (exactly like build_editor.sh for CodeMirror 6): the
# produced bundle is a committed static artifact, imported directly by
# playground/render_docs.mjs when it renders docs/guide/*.md into HTML pages.
# Nothing fetches it at serve time and nothing installs it at gate time — the
# committed file IS the dependency, so the guide render step needs no network.
#
# Re-roll the bundle only when bumping the marked version.  Requires node (v24
# recommended) + network for `npm install` / `npx esbuild`.
#
# Pinned package (installed at last roll):
#   marked 18.0.11
# Bundle: single minified ESM, ~40 KB.
set -euo pipefail

MARKED_VERSION="${MARKED_VERSION:-18.0.11}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/marked-build"
VENDOR_DIR="$SCRIPT_DIR/vendor/marked"

mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

# Facade re-exporting exactly the marked API surface render_docs.mjs uses.
cat > marked-entry.js <<'ENTRY'
export { Marked, marked } from 'marked';
ENTRY

echo "==> npm install marked@$MARKED_VERSION"
npm install --no-audit --no-fund "marked@$MARKED_VERSION"

echo "==> esbuild -> single minified ESM bundle"
npx --yes esbuild@0.25 marked-entry.js --bundle --format=esm --minify \
  --outfile=marked-bundle.js --log-level=warning \
  --banner:js="// marked $MARKED_VERSION — vendored single-ESM bundle for the Medaka docs renderer. Generated by playground/build_marked.sh (do not edit by hand)."

mkdir -p "$VENDOR_DIR"
cp marked-bundle.js "$VENDOR_DIR/marked.js"

size=$(wc -c < "$VENDOR_DIR/marked.js" | tr -d ' ')
echo "==> Vendored $VENDOR_DIR/marked.js ($size bytes)"
echo "==> Done. (marked-build/ is gitignored; the bundle is committed.)"
